{% set name = "baumwelch" %}
{% set version = "0.3.1" %}

package: 
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://www.opengrm.org/twiki/pub/GRM/BaumWelchDownload/{{ name }}-{{ version }}.tar.gz
  sha256: 6895127c6ecbc0a40215dfb8d6bbf29e9ea5d7fbd274397ef048dac2c65ee91f
  
build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
  host:
    - openfst ==1.7.6
  run:
    - openfst ==1.7.6

test:
  commands:
    - baumwelchtrain --helpshort || [[ $? == 1 ]]
    - baumwelchdecode --helpshort || [[ $? == 1 ]]

about:
  home: http://bauwmelch.opengrm.org
  license: Apache-2.0
  license_file: LICENSE
  summary: Baum-Welch/expectation-maximization training and decoding
  description: |
    A library for estimating the parameters of a discrete HMM
  doc_url: http://www.opengrm.org/twiki/bin/view/GRM/BaumWelchDocs

extra:
  recipe-maintainers:
    - kylebgorman
