{% set name = "baumwelch" %}
{% set version = "0.3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://206.196.111.47/twiki/pub/GRM/BaumWelchDownload/{{ name }}-{{ version }}.tar.gz
  sha256: 80cb35a7d625cf471bd874db0a01ff649261b87a05b409aa958164601bb99a71
  patches:
    - patches/0001-Add-CMake-files.patch  # [win]

build:
  number: 0

requirements:
  build:
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - make                    # [unix]
    - gnuconfig               # [unix]
    - cmake                   # [win]
    - ninja                   # [win]
    - m2-patch                # [win]
  host:
    - openfst ==1.8.4
    - dlfcn-win32             # [win]
    - icu                     # [win]
    - zlib                    # [win]
  run:
    - openfst ==1.8.4
    - ucrt                    # [win]

{% set baumwelch_binaries = [
    "baumwelchdecode", "baumwelchrandomize", "baumwelchtrain"
] %}

test:
  commands:
    # binaries:
    {% for each_bin in baumwelch_binaries %}
      # If behaving properly these will have return code 1.
    - {{ each_bin }} --helpshort >/dev/null || [[ $? == 1 ]]       # [unix]
    - {{ each_bin }} --helpshort & if errorlevel 1 ( exit /b 0)    # [win]
    {% endfor %}

about:
  home: http://baumwelch.opengrm.org
  license: Apache-2.0
  license_file: LICENSE
  summary: Baum-Welch/expectation-maximization training and decoding
  description: |
    A library for estimating the parameters of a discrete HMM
  doc_url: http://www.opengrm.org/twiki/bin/view/GRM/BaumWelchDocs

extra:
  recipe-maintainers:
    - kylebgorman
    - mmcauliffe
