{% set name = "baumwelch" %}
{% set version = "0.3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://www.opengrm.org/twiki/pub/GRM/BaumWelchDownload/{{ name }}-{{ version }}.tar.gz
  sha256: b18ab010af0c1663a475be2dcc285367a5078b496e10ad040d019901b19e62b8

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
  host:
    - openfst ==1.8.2
  run:
    - openfst ==1.8.2

test:
  commands:
    - baumwelchdecode --helpshort || [[ $? == 1 ]]
    - baumwelchrandomize --helpshort || [[ $? == 1 ]]
    - baumwelchtrain --helpshort || [[ $? == 1 ]]

about:
  home: http://bauwmelch.opengrm.org
  license: Apache-2.0
  license_file: LICENSE
  summary: Baum-Welch/expectation-maximization training and decoding
  description: |
    A library for estimating the parameters of a discrete HMM
  doc_url: http://www.opengrm.org/twiki/bin/view/GRM/BaumWelchDocs

extra:
  recipe-maintainers:
    - kylebgorman
