{% set name = "baumwelch" %}
{% set version = "0.3.2" %}

package: 
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://www.opengrm.org/twiki/pub/GRM/BaumWelchDownload/{{ name }}-{{ version }}.tar.gz
  sha256: bb82a764834dfe2f6fbd76fea0cbfef12b6be091a8295212108014ca3a14ff11
  
build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
  host:
    - openfst ==1.7.7
  run:
    - openfst ==1.7.7

test:
  commands:
    - baumwelchdecode --helpshort || [[ $? == 1 ]]
    - baumwelchrandomize --helpshort || [[ $? == 1 ]]
    - baumwelchtrain --helpshort || [[ $? == 1 ]]

about:
  home: http://bauwmelch.opengrm.org
  license: Apache-2.0
  license_file: LICENSE
  summary: Baum-Welch/expectation-maximization training and decoding
  description: |
    A library for estimating the parameters of a discrete HMM
  doc_url: http://www.opengrm.org/twiki/bin/view/GRM/BaumWelchDocs

extra:
  recipe-maintainers:
    - kylebgorman
