build_platform:
  osx_arm64: osx_64
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
test_on_native_only: true
travis:
  secure:
    BINSTAR_TOKEN: E06XDLHSYhzBV4B6F1jyoyNk1D4x+u8M5mayOmslPEw8CkGFpTMlG5JJzdZnMWTQB5GS3sX2N4nLgcdbcxVNAscaTQmbMmLmMgZasgMDT3kCcKhW5ypq6xg6MCNMxzxDmhhamzVunFXTzIIym5bklrTMNKUKUQO3jpe2L4YRohUIFqR+Ud/4QTwp19/qzXxXbe41TpZAoMdVCcMPIUP4r4q8Zpk3IKjWo3F6GnJ8BX6OWcswlNUHJuCmlryo+ED/IJBzzu1BkTI3qlmkfU1AwFX2I0FDzt+wQyOXJ2lsy68NaWfT3NwyIabcO1C1OIfxEZchHmpXqvA0FdYkZT05YGkcmwWLw+FjXt7XipJpZdnveRBcvXoIdJY92aY+vmG6xetxnoRebQGhWV9NlcdnNdGvIsYdl+aLDuhEfcmga4zU91+HLcPBnkzr6sFGcJ7My5lbU9Y3toI9ORSuHDgZvTk7SVbqEjReKpKXm2KLDeqYOe/2fezLQ12bXWtm+8WEy32SNEiFbcZGgYxgJk/qGPU+e+xFdJY8GuXkCimi6YhXZ24ujbJhrPkBmin9NIRVlTB1t9iTQmDtQR1mbCMlamDZ56QZS2VbiTzZXg9Yoi1DAZRTNh446MNw0YWOC5RJHVKkIUgQFZwCNe6T0bDNwa+M+EpK/1ownbSLhYUhdzg=
